<div class="wrap wpeh-pi-settings">
    <h1>Plugin Disabler</h1>

    <h2>Home Page</h2>
	<form method="post">
		<?php wp_nonce_field( 'pi_hp_nonce_action', 'pi_hp_nonce_field' ); ?>
    	<table class="widefat importers striped">
	        <tbody>
	        	<?php 
	        		$plugins = get_option('active_plugins', []);

	        		$k = array_search( 'wpeh-plugin-isolator/wpeh_plugin_isolator.php', $plugins );
					unset($plugins[$k]);

					$deactivatedPlugins = get_option('pi_hp_deactivated_plugins', []);
					$deactivatedPlugins = (!empty($deactivatedPlugins)?$deactivatedPlugins:[]);

	        		if(!empty($plugins)): 
	        			foreach($plugins as $plugin):
	        				$pluginData = get_plugin_data( WP_PLUGIN_DIR .'/'. $plugin ,  ['Version' => 'Version'], false);
	        	?>
					            <tr class="importer-item">
					                <td class="import-system">
					                    <span class="importer-title"><?php echo $pluginData['Name']; ?></span>
					                </td>
					                <td class="desc">
					                    <span class="importer-desc"><?php echo $pluginData['Description']; ?></span>
					                </td>
					                <td>
					                	<div class="onoffswitch">
										    <input type="checkbox" name="hp_deactivate_plugins[]" class="onoffswitch-checkbox" 
										    id="<?php echo strtolower(str_replace(['/','.'],'_', $plugin)).'_hp'; ?>" 
										    <?php echo (in_array($plugin, $deactivatedPlugins)?'checked':''); ?> 
										    value="<?php echo $plugin; ?>">
										    <label class="onoffswitch-label" for="<?php echo strtolower(str_replace(['/','.'],'_', $plugin)).'_hp'; ?>">
										        <span class="onoffswitch-inner"></span>
										        <span class="onoffswitch-switch"></span>
										    </label>
										</div>
					                </td>
					            </tr>
	            <?php 
	            		endforeach;
	            	endif;	
	            ?> 
	        </tbody>
    	</table>
    	<input type="submit" class="pi-settings-button" id="pi-save-hp-settings" value="Save Changes on Homepage">
    </form>	

    <hr />

    <h2>Other Pages / Pages that have no ID</h2>
	<form method="post">
		<?php wp_nonce_field( 'pi_op_nonce_action', 'pi_op_nonce_field' ); ?>
    	<table class="widefat importers striped">
	        <tbody>
	        	<?php 
	        		$plugins = get_option('active_plugins', []);

	        		$k = array_search( 'wpeh-plugin-disabler/wpeh-plugin-disabler.php', $plugins );
					unset($plugins[$k]);

					$deactivatedPlugins = get_option('pi_op_deactivated_plugins', []);
					$deactivatedPlugins = (!empty($deactivatedPlugins)?$deactivatedPlugins:[]);

	        		if(!empty($plugins)): 
	        			foreach($plugins as $plugin):
	        				$pluginData = get_plugin_data( WP_PLUGIN_DIR .'/'. $plugin ,  ['Version' => 'Version'], false);
	        	?>
					            <tr class="importer-item">
					                <td class="import-system">
					                    <span class="importer-title"><?php echo $pluginData['Name']; ?></span>
					                </td>
					                <td class="desc">
					                    <span class="importer-desc"><?php echo $pluginData['Description']; ?></span>
					                </td>
					                <td>
					                	<div class="onoffswitch">
										    <input type="checkbox" name="op_deactivate_plugins[]" class="onoffswitch-checkbox" 
										    id="<?php echo strtolower(str_replace(['/','.'],'_', $plugin)).'_op'; ?>" 
										    <?php echo (in_array($plugin, $deactivatedPlugins)?'checked':''); ?> 
										    value="<?php echo $plugin; ?>">
										    <label class="onoffswitch-label" for="<?php echo strtolower(str_replace(['/','.'],'_', $plugin)).'_op'; ?>">
										        <span class="onoffswitch-inner"></span>
										        <span class="onoffswitch-switch"></span>
										    </label>
										</div>
					                </td>
					            </tr>
	            <?php 
	            		endforeach;
	            	endif;	
	            ?> 
	        </tbody>
    	</table>
    	<input type="submit" class="pi-settings-button" id="pi-save-hp-settings"  value="Save Changes on Other Pages / Pages that have no ID">
    </form>	

    <hr />

    <h2>Not working? Maybe becuase of the server file Permission. Follow Steps below.</h2>
    <ol>
	  <li>Login to your File Manager and go to your-root-directory/wp-contents/mu-plugins.</li>
	  <li>Create a file and name it "pdm.php".</li>
	  <li>Copy the php snippet below, open the pdm.php you have create from the previous step and paste the code there.</li> 
	  <li>And that's it! You are all set!</li>
	</ol> 
    <blockquote>
    	<textarea class="mu-snippet"><?php echo "&lt;?php 
/*
Plugin Name: Plugin Disabler Snippet
Description: Snippet generated by Plugin Disabler
Author: Christian Bautista
Version: 1.0
Author URI: https://www.christianbautista.info/plugins/plugin-disabler
*/
require_once(WP_PLUGIN_DIR.\"/plugin-disabler/classes/plugin-disabler-mu.php\");" 
		?></textarea>
    </blockquote>

    <hr />
    
    <h2>Help me continue my work, please.</h2>
		<form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
		<input type="hidden" name="cmd" value="_s-xclick" />
		<input type="hidden" name="hosted_button_id" value="8KWGGP6BDP7PU" />
		<input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_donateCC_LG.gif" border="0" name="submit" title="PayPal - The safer, easier way to pay online!" alt="Donate with PayPal button" />
		<img alt="" border="0" src="https://www.paypal.com/en_PH/i/scr/pixel.gif" width="1" height="1" />
	</form>

</div>